#!/usr/bin/env bash
# =============================================================================
# control.sh — Generic Docker stack control (auto-detecting)
#
# Usage:
#   ./control.sh setup [--force] [dev|prod]   create/refresh .env, start stack
#   ./control.sh start                        start the stack
#   ./control.sh stop                         stop and remove containers
#   ./control.sh restart                      restart containers (no rebuild)
#   ./control.sh rebuild                      git pull + rebuild images + recreate
#   ./control.sh status                       show container + version status
#   ./control.sh logs [service]               tail logs (default: all services)
#   ./control.sh reset [--yes]                DESTRUCTIVE wipe + fresh setup
#   ./control.sh help                         show this help
#
# No configuration file needed — this script inspects the repo and detects:
#   * framework   (laravel when artisan+composer.json exist, node for any
#                  package.json, otherwise generic)
#   * compose     which docker-compose files exist (dev/prod/override)
#   * main service (docker compose config --services, preferring a name that
#                  matches the repo, then app/web, then the first service)
#   * secrets     empty *_KEY / *_SECRET / *_PASSWORD / *_TOKEN / APP_KEY
#                  entries in .env(.example) are generated during setup
#   * version     APP_VERSION/GIT_SHA build args are injected only when the
#                  Dockerfile / compose files actually use them
#   * reset scope SQLite files and gitignored data dirs that exist on disk
#
# Generated by the docker-control-sh skill. Repo-specific hooks such as admin
# password resets were intentionally removed; re-add them per project if needed.
# =============================================================================

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

# ---------------------------------------------------------------------------
# -- Helpers ---------------------------------------------------------------
# ---------------------------------------------------------------------------

log()    { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
warn()   { printf '\033[1;33m!!  %s\033[0m\n' "$*"; }
die()    { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# -- Detection -------------------------------------------------------------
# ---------------------------------------------------------------------------

FRAMEWORK="generic"
MAIN_SERVICE=""
COMPOSE_FILES="docker-compose.yml"

detect_framework() {
    if [ -f artisan ] && [ -f composer.json ]; then
        FRAMEWORK="laravel"
    elif [ -f package.json ]; then
        FRAMEWORK="node"
    else
        FRAMEWORK="generic"
    fi
}

detect_main_service() {
    local services names preferred
    if ! services="$(docker compose config --services 2>/dev/null)"; then
        MAIN_SERVICE="app"
        return
    fi
    [ -z "$services" ] && { MAIN_SERVICE="app"; return; }
    names="$(basename "$PROJECT_DIR")
app
web
server
www"

    preferred="$(printf '%s\n' "$names" | while read -r name; do
        printf '%s\n' "$services" | grep -qx "$name" && { printf '%s' "$name"; break; }
    done)" || true
    if [ -n "$preferred" ]; then
        MAIN_SERVICE="$preferred"
    else
        MAIN_SERVICE="$(printf '%s\n' "$services" | head -1)"
    fi
}

# Collect the compose files that actually exist, preferring explicit overrides.
detect_compose_files() {
    local files="" candidate
    for candidate in docker-compose.yml docker-compose.prod.yml docker-compose.override.yml compose.yaml compose.yml; do
        if [ -f "$candidate" ]; then
            [ -n "$files" ] && files="$files:"
            files="$files$candidate"
        fi
    done
    if [ -n "$files" ]; then
        COMPOSE_FILES="$files"
    fi
    return 0
}

# Does the Dockerfile / compose setup consume APP_VERSION or GIT_SHA?
uses_version_args() {
    grep -qsE 'APP_VERSION|GIT_SHA' Dockerfile Dockerfile.* 2>/dev/null ||
        grep -qsE '\$\{?(APP_VERSION|GIT_SHA)\}?' docker-compose*.yml compose.*.y?ml 2>/dev/null
}

# ---------------------------------------------------------------------------
# -- Env helpers ------------------------------------------------------------
# ---------------------------------------------------------------------------

ENV_FILE=".env"
HAS_ENV_EXAMPLE=0
[ -f .env.example ] && HAS_ENV_EXAMPLE=1

get_env() {
    grep -E "^${1}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true
}

set_env() {
    local key="$1" value="$2"
    if grep -qE "^${key}=" "$ENV_FILE"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
    else
        printf '\n%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
}

unset_env() {
    sed -i "/^${1}=/d" "$ENV_FILE"
}

# Does the key exist in .env or .env.example?
has_key() {
    if grep -qE "^${1}=" "$ENV_FILE" 2>/dev/null; then
        return 0
    fi
    [ -f .env.example ] && grep -qE "^${1}=" .env.example 2>/dev/null
}

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24
    else
        node -e "console.log(require('crypto').randomBytes(24).toString('hex'))"
    fi
}

# Keys from a file that are set to an empty value AND look like secrets.
empty_secret_keys() {
    local file="$1"
    [ -f "$file" ] || return 0
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=$' "$file" | cut -d= -f1 |
        grep -E '(_KEY|_SECRET|_PASSWORD|_TOKEN|APP_KEY|SECRET)$' || true
}

# Fill every empty secret-looking key in .env with a generated value.
fill_secrets() {
    local key generated any=0
    for key in $(empty_secret_keys "$ENV_FILE"); do
        generated="$(generate_secret)"
        set_env "$key" "$generated"
        log "Generated ${key}"
        any=1
    done
    if [ "$any" -eq 1 ]; then
        log "Secrets written to ${ENV_FILE}."
    fi
    return 0
}

# Generate APP_KEY for Laravel via the running stack (like script.1) or a
# one-off run when the app container isn't up yet.
ensure_app_key() {
    [ "$FRAMEWORK" != "laravel" ] && return 0
    if grep -qE '^APP_KEY=.+' "$ENV_FILE" 2>/dev/null; then
        return 0
    fi
    log "Generating APP_KEY (Laravel)..."
    if [ "$(get_env APP_ENV)" = "production" ]; then
        docker compose run --rm --no-deps --entrypoint php \
            -v "$PROJECT_DIR/.env:/var/www/html/.env" \
            "$MAIN_SERVICE" artisan key:generate --force --no-interaction 2>/dev/null \
        || warn "Could not generate APP_KEY in a one-off container — the app entrypoint will do it on first boot."
    else
        docker compose exec -T "$MAIN_SERVICE" php artisan key:generate --force --no-interaction 2>/dev/null \
        || warn "App container not running — APP_KEY will be generated on first boot."
    fi
}

# Create docker-compose.yml from the example when the real file is missing.
# The real file is gitignored, so fresh clones only ship the example.
ensure_compose_file() {
    if [ -f docker-compose.yml ]; then
        return
    fi
    if [ -f docker-compose.yml.example ]; then
        cp docker-compose.yml.example docker-compose.yml
        log "Created docker-compose.yml from docker-compose.yml.example"
    else
        die "No docker-compose.yml and no docker-compose.yml.example to copy from."
    fi
}

ensure_env_file() {
    if [ -f "$ENV_FILE" ]; then
        return
    fi
    if [ "$HAS_ENV_EXAMPLE" -eq 1 ]; then
        cp .env.example "$ENV_FILE"
        log "Created .env from .env.example"
        fill_secrets
    else
        # No .env.example — create an empty .env so the stack can start.
        # dumbdock needs no environment file; no secrets are generated.
        printf '# Created by control.sh — no .env.example present.\n' > "$ENV_FILE"
        log "Created empty .env (no .env.example present)"
    fi
}

# ---------------------------------------------------------------------------
# -- Stack helpers ----------------------------------------------------------
# ---------------------------------------------------------------------------

require_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        die "Docker is not installed or not in PATH."
    fi
    if ! docker compose version >/dev/null 2>&1; then
        die "Docker Compose (v2, 'docker compose') is not available."
    fi
}

# Ask a yes/no question; default "no".
confirm() {
    printf "%s [y/N] " "$1"
    read -r answer || true
    case "$answer" in
        y|Y|yes|YES) return 0 ;;
        *) return 1 ;;
    esac
}

# Wait until the main service is usable. Framework-aware: Laravel is ready
# once `php artisan` works (vendor present). Node/generic fall back to the
# container being up.
wait_ready() {
    local i
    log "Waiting for the ${MAIN_SERVICE} container..."
    for i in $(seq 1 300); do
        if [ "$FRAMEWORK" = "laravel" ]; then
            if docker compose exec -T "$MAIN_SERVICE" php artisan --version >/dev/null 2>&1; then
                log "App container is ready."
                return 0
            fi
        else
            if docker compose ps --services 2>/dev/null | grep -qx "$MAIN_SERVICE" &&
               docker compose ps "$MAIN_SERVICE" 2>/dev/null | grep -q "Up"; then
                log "App container is ready."
                return 0
            fi
        fi
        sleep 1
    done
    warn "App container not ready after 300s — check './control.sh logs ${MAIN_SERVICE}'."
}

# ---------------------------------------------------------------------------
# -- setup -----------------------------------------------------------------
# ---------------------------------------------------------------------------

cmd_setup() {
    local force=0 mode="dev"
    case "${1:-}" in
        --force) force=1 ;;
        dev|prod) mode="$1" ;;
        "") ;;
        *) die "Unknown setup option '${1:-}' (expected --force, dev, prod)" ;;
    esac
    case "${2:-}" in
        dev|prod) mode="$2" ;;
        --force)
            if [ "$force" -eq 0 ]; then
                force=1
            else
                die "Duplicate --force flag"
            fi
            ;;
        "") ;;
        *) die "Unknown setup option '${2:-}' (expected --force, dev, prod)" ;;
    esac

    if [ -f "$ENV_FILE" ] && [ "$force" -eq 1 ]; then
        warn "Overwriting existing .env (backing up to .env.bak)..."
        cp "$ENV_FILE" .env.bak
    fi

    ensure_env_file
    fill_secrets

    # prod only behaves specially when prod/override compose files exist
    if [ "$mode" = "prod" ]; then
        if [ -f docker-compose.prod.yml ] || [ -f docker-compose.override.yml ]; then
            has_key APP_ENV && set_env APP_ENV "production"
            set_env COMPOSE_FILE "$COMPOSE_FILES"
            log "Production mode: COMPOSE_FILE=$COMPOSE_FILES"
            if grep -qE '^APP_DEBUG=true' "$ENV_FILE" 2>/dev/null; then
                warn "APP_DEBUG=true is set — consider false in production."
            fi
        else
            warn "No docker-compose.prod.yml / docker-compose.override.yml found — treating prod like dev."
            has_key APP_ENV && set_env APP_ENV "local"
            unset_env COMPOSE_FILE
        fi
    else
        has_key APP_ENV && set_env APP_ENV "local"
        unset_env COMPOSE_FILE
        if [ "$FRAMEWORK" = "laravel" ] && ! grep -qE '^APP_PORT=' "$ENV_FILE" 2>/dev/null; then
            set_env APP_PORT 8080
        fi
    fi

    require_docker
    ensure_compose_file
    detect_main_service
    docker compose config --quiet || die "docker compose config failed — check your compose files."
    docker compose up -d
    wait_ready
    ensure_app_key

    local url port
    port="$(get_env APP_PORT)"
    url="$(get_env APP_BASE_URL)"
    if [ -n "$port" ]; then
        log "Done. Stack available at http://localhost:${port}"
    elif [ -n "$url" ]; then
        log "Done. Stack available at ${url}"
    else
        log "Done."
    fi
}

# ---------------------------------------------------------------------------
# -- start / stop / restart --------------------------------------------------
# ---------------------------------------------------------------------------

cmd_start() {
    require_docker
    ensure_compose_file
    ensure_env_file
    detect_main_service
    docker compose up -d
    wait_ready
    ensure_app_key
}

cmd_stop() {
    require_docker
    docker compose down
}

cmd_restart() {
    require_docker
    docker compose restart
}

# ---------------------------------------------------------------------------
# -- rebuild ----------------------------------------------------------------
# ---------------------------------------------------------------------------

cmd_rebuild() {
    require_docker
    ensure_compose_file
    detect_main_service

    # Pull the latest code first (skips gracefully when there's no remote or
    # the repo is on a detached HEAD).
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        log "Pulling latest code (git pull --ff-only)..."
        git pull --ff-only 2>&1 || warn "git pull failed — continuing with current code."
    fi

    # Flag silent drift when a tracked example compose file diverges from the
    # (possibly gitignored) real one.
    if [ -f docker-compose.yml ] && [ -f docker-compose.yml.example ]; then
        if ! diff -q docker-compose.yml docker-compose.yml.example >/dev/null 2>&1; then
            warn "docker-compose.yml differs from docker-compose.yml.example (gitignored file drifts silently):"
            diff docker-compose.yml docker-compose.yml.example || true
            warn "Review the diff before continuing."
        fi
    fi

    # Bake the git version + commit into the image when the image consumes them.
    local version_args=""
    if uses_version_args; then
        local app_version git_sha
        app_version="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
        app_version="${app_version#v}"
        git_sha="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
        log "Rebuilding (v${app_version} @ ${git_sha})..."
        version_args="--build-arg APP_VERSION=$app_version --build-arg GIT_SHA=$git_sha"
    else
        log "Rebuilding images..."
    fi

    docker compose down
    docker compose build --pull $version_args
    docker compose up -d --force-recreate
    wait_ready

    # A rebuild can complete while a container crash-loops; surface it.
    sleep 5
    if docker compose ps 2>/dev/null | grep -q "Restarting"; then
        warn "=== One or more containers are crash-looping:"
        docker compose ps | grep "Restarting" || true
        warn "Check the failing service logs: ./control.sh logs <service>"
    fi
}

# ---------------------------------------------------------------------------
# -- status / logs -----------------------------------------------------------
# ---------------------------------------------------------------------------

cmd_status() {
    require_docker
    log "Container status:"
    docker compose ps

    if docker compose ps --services 2>/dev/null | grep -qx "$MAIN_SERVICE" &&
       docker compose ps "$MAIN_SERVICE" 2>/dev/null | grep -q "Up"; then
        local git_version env_version
        git_version="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
        env_version="$(get_env APP_VERSION)" || env_version=""
        log "Running version: ${env_version:-$git_version}"
    fi
}

cmd_logs() {
    local service="${1:-}"
    require_docker
    if [ -n "$service" ]; then
        docker compose logs -f --tail=100 "$service"
    else
        docker compose logs -f --tail=100
    fi
}

# ---------------------------------------------------------------------------
# -- reset ------------------------------------------------------------------
# ---------------------------------------------------------------------------

cmd_reset() {
    local force=0
    [ "${1:-}" = "--yes" ] && force=1

    require_docker
    ensure_env_file

    # Find obvious sqlite files shallow-diving, ignoring .git/vendor/node_modules.
    local sqlite_files
    sqlite_files="$(find . -maxdepth 3 -name '*.sqlite*' \
        -not -path './.git/*' -not -path './vendor/*' -not -path './node_modules/*' 2>/dev/null)" || true

    # Gitignored data dirs that exist on disk and are safe candidates to wipe.
    local data_dirs=""
    local dir
    for dir in data database storage tmp runtime; do
        if [ -d "$dir" ] && git check-ignore -q "$dir" 2>/dev/null; then
            data_dirs="$data_dirs $dir"
        fi
    done

    warn ""
    warn "============================================================"
    warn " DESTRUCTIVE — this will DELETE:"
    warn "   • All containers and named volumes  (docker compose down -v)"
    [ -n "$sqlite_files" ] && warn "   • SQLite databases:${sqlite_files//$'\n'/ }"
    [ -n "$data_dirs" ] && warn "   • Gitignored data dirs:$data_dirs"
    if [ "$HAS_ENV_EXAMPLE" -eq 1 ]; then
        warn "   • .env (re-created fresh from .env.example)"
    fi
    warn ""
    warn " This CANNOT BE UNDONE."
    warn "============================================================"
    warn ""
    if [ "$force" -ne 1 ]; then
        confirm "Are you sure you want to wipe the stack?" || { warn "Aborted."; exit 0; }
    fi

    docker compose down -v

    # SQLite files may be root-owned from container runs; fall back to a root
    # alpine container when a plain rm fails.
    local f
    for f in $sqlite_files; do
        if ! rm -f "$f" 2>/dev/null; then
            docker run --rm -v "$PROJECT_DIR:/app" alpine:latest \
                sh -c "rm -f \"/app/${f#./}\"" >/dev/null 2>&1 || true
        fi
    done

    for dir in $data_dirs; do
        if ! rm -rf "$dir" 2>/dev/null; then
            docker run --rm -v "$PROJECT_DIR:/app" alpine:latest \
                sh -c "rm -rf \"/app/$dir/*\"" >/dev/null 2>&1 || true
            rm -rf "$dir" 2>/dev/null || true
        fi
    done

    log "Stack wiped. Re-running setup..."
    cmd_setup --force
    log "Done. Run './control.sh start' if the stack is not already running."
}

# ---------------------------------------------------------------------------
# -- Dispatch ---------------------------------------------------------------
# ---------------------------------------------------------------------------

detect_framework
detect_compose_files

usage() {
    sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
}

case "${1:-}" in
    ""|-h|--help|help) usage ;;
    setup)            cmd_setup "${2:-}" "${3:-}" ;;
    start)            cmd_start ;;
    stop)             cmd_stop ;;
    restart)          cmd_restart ;;
    rebuild)          cmd_rebuild ;;
    status)           detect_main_service; cmd_status ;;
    logs)             cmd_logs "${2:-}" ;;
    reset)            cmd_reset "${2:-}" ;;
    *) die "Unknown command '${1:-}'. Run './control.sh help'." ;;
esac